// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/algolia.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/analytics.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/verified-reviews.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$5 from "./apps/site.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/meiasola/extensionGetModelVariants.ts";
import * as $$$2 from "./loaders/meiasola/extensionProductListingPage.ts";
import * as $$$3 from "./loaders/meiasola/myStylePosts.ts";
import * as $$$4 from "./loaders/meiasola/notFoundProductListingPage.ts";
import * as $$$$$$0 from "./sections/Category/BrandBanner.tsx";
import * as $$$$$$1 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$2 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryTextReadMore.tsx";
import * as $$$$$$4 from "./sections/Content/Benefits.tsx";
import * as $$$$$$5 from "./sections/Content/CustomBenefitsBar.tsx";
import * as $$$$$$6 from "./sections/Content/Faq.tsx";
import * as $$$$$$7 from "./sections/Content/Logos.tsx";
import * as $$$$$$8 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$9 from "./sections/Footer/Footer.tsx";
import * as $$$$$$10 from "./sections/Header/Header.tsx";
import * as $$$$$$11 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$12 from "./sections/Images/Carousel.tsx";
import * as $$$$$$13 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$14 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$15 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$16 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$17 from "./sections/MeiaSola/BrandCarousel.tsx";
import * as $$$$$$18 from "./sections/MeiaSola/Categories.tsx";
import * as $$$$$$19 from "./sections/MeiaSola/ChooseYourSize.tsx";
import * as $$$$$$20 from "./sections/MeiaSola/Collections.tsx";
import * as $$$$$$21 from "./sections/MeiaSola/ContactUs.tsx";
import * as $$$$$$22 from "./sections/MeiaSola/InstagramCarousel.tsx";
import * as $$$$$$23 from "./sections/MeiaSola/InstitutionalContent.tsx";
import * as $$$$$$24 from "./sections/MeiaSola/InstitutionalMenu.tsx";
import * as $$$$$$25 from "./sections/MeiaSola/MyStyle.tsx";
import * as $$$$$$26 from "./sections/MeiaSola/NewCollection.tsx";
import * as $$$$$$27 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$28 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$29 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$30 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$31 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$32 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$33 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$34 from "./sections/ProxyIframe/ProxyIframe.tsx";
import * as $$$$$$35 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$36 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$37 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "site/loaders/Layouts/ProductCard.tsx": $$$0,
    "site/loaders/meiasola/extensionGetModelVariants.ts": $$$1,
    "site/loaders/meiasola/extensionProductListingPage.ts": $$$2,
    "site/loaders/meiasola/myStylePosts.ts": $$$3,
    "site/loaders/meiasola/notFoundProductListingPage.ts": $$$4,
  },
  "sections": {
    "site/sections/Category/BrandBanner.tsx": $$$$$$0,
    "site/sections/Category/CategoryBanner.tsx": $$$$$$1,
    "site/sections/Category/CategoryList.tsx": $$$$$$2,
    "site/sections/Category/CategoryTextReadMore.tsx": $$$$$$3,
    "site/sections/Content/Benefits.tsx": $$$$$$4,
    "site/sections/Content/CustomBenefitsBar.tsx": $$$$$$5,
    "site/sections/Content/Faq.tsx": $$$$$$6,
    "site/sections/Content/Logos.tsx": $$$$$$7,
    "site/sections/Content/Testimonials.tsx": $$$$$$8,
    "site/sections/Footer/Footer.tsx": $$$$$$9,
    "site/sections/Header/Header.tsx": $$$$$$10,
    "site/sections/Images/BannerGrid.tsx": $$$$$$11,
    "site/sections/Images/Carousel.tsx": $$$$$$12,
    "site/sections/Images/ImageGallery.tsx": $$$$$$13,
    "site/sections/Images/ShoppableBanner.tsx": $$$$$$14,
    "site/sections/Links/LinkTree.tsx": $$$$$$15,
    "site/sections/Links/Shortcuts.tsx": $$$$$$16,
    "site/sections/MeiaSola/BrandCarousel.tsx": $$$$$$17,
    "site/sections/MeiaSola/Categories.tsx": $$$$$$18,
    "site/sections/MeiaSola/ChooseYourSize.tsx": $$$$$$19,
    "site/sections/MeiaSola/Collections.tsx": $$$$$$20,
    "site/sections/MeiaSola/ContactUs.tsx": $$$$$$21,
    "site/sections/MeiaSola/InstagramCarousel.tsx": $$$$$$22,
    "site/sections/MeiaSola/InstitutionalContent.tsx": $$$$$$23,
    "site/sections/MeiaSola/InstitutionalMenu.tsx": $$$$$$24,
    "site/sections/MeiaSola/MyStyle.tsx": $$$$$$25,
    "site/sections/MeiaSola/NewCollection.tsx": $$$$$$26,
    "site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$27,
    "site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$28,
    "site/sections/Newsletter/Newsletter.tsx": $$$$$$29,
    "site/sections/Product/ProductDetails.tsx": $$$$$$30,
    "site/sections/Product/ProductShelf.tsx": $$$$$$31,
    "site/sections/Product/SearchResult.tsx": $$$$$$32,
    "site/sections/Product/Wishlist.tsx": $$$$$$33,
    "site/sections/ProxyIframe/ProxyIframe.tsx": $$$$$$34,
    "site/sections/Social/InstagramPosts.tsx": $$$$$$35,
    "site/sections/Social/WhatsApp.tsx": $$$$$$36,
    "site/sections/Theme/Theme.tsx": $$$$$$37,
  },
  "apps": {
    "site/apps/deco/algolia.ts": $$$$$$$$$$$0,
    "site/apps/deco/analytics.ts": $$$$$$$$$$$1,
    "site/apps/deco/verified-reviews.ts": $$$$$$$$$$$2,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$3,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$4,
    "site/apps/site.ts": $$$$$$$$$$$5,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
